project_id = "xgghtqxrebhmdwisvnhj"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "https://eazy-loans.com"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://eazy-loans.com", "https://xgghtqxrebhmdwisvnhj.supabase.co", "http://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email addresses.
# If disabled, only the new email is required to confirm.
double_confirm_email_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = true

# Configure SMTP for the auth system.
[auth.email.smtp]
host = "smtp.resend.com"
port = 587
user = "resend"
# If `enable_signup` is `false`, then only this admin email can sign up.
admin_email = "admin@example.com"
# `sender_name` is the friendly name that shows up in the email address.
sender_name = "Eazy Loan"

# Use pre-defined map of configuration, check out these links for more info:
# https://supabase.com/docs/guides/auth/auth-smtp#mailtrap
# https://supabase.com/docs/guides/auth/auth-smtp#gmail
[auth.email.template.invite]
subject = "You have been invited"
content_path = "./supabase/templates/invite.html"

[auth.email.template.confirmation]
subject = "Confirm Your Email - Eazy Loan"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.recovery]
subject = "Reset Your Password - Eazy Loan"
content_path = "./supabase/templates/recovery.html"

[auth.email.template.magic_link]
subject = "Your Magic Link"
content_path = "./supabase/templates/magic_link.html"

[auth.email.template.email_change]
subject = "Confirm Email Change"
content_path = "./supabase/templates/email_change.html"

# Hook configuration for custom email sending
[auth.hook.send_email]
enabled = true
uri = "https://xgghtqxrebhmdwisvnhj.supabase.co/functions/v1/send-auth-email"

[functions.send-auth-email]
verify_jwt = false