// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgghtqxrebhmdwisvnhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnZ2h0cXhyZWJobWR3aXN2bmhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MjkwMDgsImV4cCI6MjA2NzAwNTAwOH0.qOjNPPmf64703MOLq6hxYcvrpyTrKKxDHZeN4dP9oQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});